#!/usr/bin/env node
/* build.mjs — produces the deployable site in dist/ (the host runs `npm run build` and
   publishes dist/; see DEPLOY.md).

   Every page except the home page is plain HTML and is copied as-is. The home page is
   a React app whose JSX (site/*.jsx + tweaks-panel.jsx) is authored for in-browser Babel,
   which leaves index.html with an empty <div id="root"> for any crawler that doesn't run
   JavaScript, and makes every visitor download + run Babel before seeing anything.
   This build:
     1. compiles those JSX files once, with the same Babel presets the browser used, into
        site/home.js (so Babel is no longer shipped to visitors);
     2. renders <App/> to HTML in Node and writes it into #root, so the full home page is
        in the HTML response; the browser then hydrates it (see the end of site/App.jsx).
   The source index.html is left untouched, so opening it directly (in-browser Babel)
   still works for design/edit sessions. */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'dist');

// Repo-only files: tooling, docs, and design-system reference material that isn't
// part of the public site (none of it is linked from a page).
const EXCLUDE = new Set([
  '.git', '.github', '.vercel', '.claude', 'node_modules', 'dist', 'scripts',
  'preview', 'uploads', 'package.json', 'package-lock.json', '.gitignore',
  'README.md', 'SKILL.md', 'DEPLOY.md', 'colors_and_type.css', '.DS_Store',
]);

function fail(msg) {
  console.error('\nBUILD FAILED: ' + msg + '\n');
  process.exit(1);
}

function copyTree(src, dst, skip) {
  fs.mkdirSync(dst, { recursive: true });
  for (const ent of fs.readdirSync(src, { withFileTypes: true })) {
    if (EXCLUDE.has(ent.name)) continue;
    const s = path.join(src, ent.name);
    const rel = path.relative(ROOT, s).split(path.sep).join('/');
    if (skip.has(rel)) continue;
    const d = path.join(dst, ent.name);
    if (ent.isDirectory()) copyTree(s, d, skip);
    else if (ent.isFile()) fs.copyFileSync(s, d);
  }
}

// ---------------------------------------------------------------------------
const indexSrc = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// The JSX files, in the order index.html loads them.
const babelTagRe = /<script type="text\/babel" src="([^"]+)"><\/script>/g;
const jsxFiles = [...indexSrc.matchAll(babelTagRe)].map(m => m[1]);
if (!jsxFiles.length) fail('no <script type="text/babel"> tags found in index.html');

// 1. Compile — same presets/plugins @babel/standalone applies to text/babel scripts.
const Babel = require('@babel/standalone');
const compiled = jsxFiles.map((file) => {
  const code = fs.readFileSync(path.join(ROOT, file), 'utf8');
  const out = Babel.transform(code, {
    filename: file,
    presets: ['react', 'env'],
    plugins: ['transform-class-properties', 'transform-object-rest-spread', 'transform-flow-strip-types'],
    comments: false,
  }).code;
  return `/* ${file} */\n${out}\n`;
});
const homeJs = '/* Generated by scripts/build.mjs from the JSX sources — edit those, not this file. */\n'
  + compiled.join(';\n');

// 2. Render <App/> to HTML. The components only touch window/document inside effects
//    and handlers, which don't run during a server render; the stubs cover the few
//    top-level references (window.X = X exports and the mount call in App.jsx).
const React = require('react');
const ReactDOMServer = require('react-dom/server');
// Hydration only works if the markup comes from the same React the page loads.
const pageReact = indexSrc.match(/assets\/vendor\/react-(\d+\.\d+\.\d+)\.production\.min\.js/);
const pageReactDom = indexSrc.match(/assets\/vendor\/react-dom-(\d+\.\d+\.\d+)\.production\.min\.js/);
if (!pageReact || !pageReactDom) fail('index.html no longer loads assets/vendor/react-<version>.production.min.js / react-dom-<version>');
for (const v of [pageReact[1], pageReactDom[1]]) {
  if (v !== React.version) fail(`index.html loads React ${v} but the build renders with ${React.version} — align package.json with assets/vendor/`);
}
let appElement = null;
const sandbox = {
  React,
  ReactDOM: {
    createRoot: () => ({ render: (el) => { appElement = el; } }),
    hydrateRoot: (_container, el) => { appElement = el; },
  },
  document: { getElementById: () => ({ hasChildNodes: () => false }) },
  console,
};
sandbox.window = sandbox;
sandbox.self = sandbox;
vm.createContext(sandbox);
try {
  vm.runInContext(homeJs, sandbox, { filename: 'site/home.js' });
} catch (e) {
  fail('evaluating the compiled home page threw: ' + (e && e.stack || e));
}
if (!appElement) fail('App.jsx never mounted anything (expected a createRoot/hydrateRoot call)');
const appHtml = ReactDOMServer.renderToString(appElement);
if (!/<h1[\s>]/.test(appHtml)) fail('rendered home page has no <h1> — refusing to ship an empty page');

// 3. Assemble dist/index.html.
let index = indexSrc;
const swap = (from, to, what) => {
  if (!index.includes(from)) fail(`index.html: couldn't find ${what}`);
  index = index.replace(from, to);
};
swap('<div id="root"></div>', `<div id="root">${appHtml}</div>`, 'the empty <div id="root"></div>');
index = index.replace(/\s*<script[^>]*src="https:\/\/unpkg\.com\/@babel\/standalone@[^"]+"[^>]*><\/script>/, '');
let first = true;
index = index.replace(/<script type="text\/babel" src="[^"]+"><\/script>\n?\s*/g, () => {
  if (!first) return '';
  first = false;
  return '<script defer src="site/home.js"></script>\n\n  ';
});
index = index.replace(/<!-- Page components\.[\s\S]*?-->/, '<!-- Page components, precompiled from the JSX sources by scripts/build.mjs -->');
for (const bad of ['text/babel', 'babel.min.js', 'unpkg.com']) {
  if (index.includes(bad)) fail(`dist/index.html still references ${bad}`);
}

// ---------------------------------------------------------------------------
fs.rmSync(OUT, { recursive: true, force: true });
copyTree(ROOT, OUT, new Set(['index.html', ...jsxFiles]));
fs.writeFileSync(path.join(OUT, 'index.html'), index);
fs.writeFileSync(path.join(OUT, 'site', 'home.js'), homeJs);

const kb = (n) => (n / 1024).toFixed(0) + ' KB';
console.log(`Built dist/ — home page pre-rendered (${kb(appHtml.length)} of HTML from ${jsxFiles.length} JSX files), `
  + `site/home.js ${kb(homeJs.length)}, React ${React.version}.`);
